dist: xenial
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - python2 -m pip install --user --upgrade pip
  - python3 -m pip install --user --upgrade pip
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
